### ISSUE TITLE
Support nerd fonts

### ISSUE THREAD

**Issue by andys8** [elisescu/tty-share#15]
It would be nice, if [nerd fonts](https://github.com/ryanoasis/nerd-fonts) could be supported. These are quite common, if people play with their setup.

![image](https://user-images.githubusercontent.com/13085980/94084598-28716380-fe06-11ea-9289-38a74e646427.png)

I haven't looked into it, but maybe it's enough to include one of the fonts and configure xterm to use it.

**Comment by andys8** [comment]
I noticed I created this issue not in https://github.com/elisescu/tty-server/issues/9 and is already worked on: https://github.com/elisescu/tty-server/pull/10/files

I experimented with `xterm.js` and [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts). It will display glyphs.

![image](https://user-images.githubusercontent.com/13085980/94087449-109ddd80-fe0e-11ea-9575-eef6efc92455.png)

###

```css
      @font-face {
        font-family: "Fira Code Nerd Font";
        src: url("fira.ttf") format("truetype");
        font-variant-ligatures: none;
      }
```

```ts
        this.xterminal = new Terminal({
            ...
            fontFamily : "Fira Code Nerd Font"
        });
```
