### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by marcoburrometo** [elisescu/tty-share#30]
Hello all!

From today https certificate is expired and i'm not able to use go.tty-share server.
Can you please renew it?

![image](https://user-images.githubusercontent.com/10879009/107633734-ca380680-6c68-11eb-822b-6acc925aaba2.png)

**Comment by ArunavhaChanda** [comment]
Same issue!
I use this every day to organize multiplayer events and this has suddenly blocked us from using tty-share. Would be super helpful if we could get this renewed!

Thanks!

**Comment by 0x326** [comment]
I just figured out how to self-host a `tty-share` server (as documented [here](https://github.com/elisescu/tty-server/tree/56e269830bd98411b18f6299761f56ab3a87f82a)):

```bash
git clone https://github.com/elisescu/tty-server.git
cd tty-server/
docker build . -t elisescu/tty-server
```

Create a `docker-compose.yml` file:
```yaml
version: '3.7'
services:
  tty_share:
    image: elisescu/tty-server
    cap_drop:
      - ALL
    environment:
      URL: 'https://${DOMAIN}:44392'
    expose:
      - '6543'
      - '5000'
    ports:
      - '127.0.0.1:44393:6543'
```

```bash
docker-compose up -d
tty-share --server localhost:44393 --useTLS=false
```
